## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect;
        ddl-auto: update
    show-sql: true
  database:
    driverClassName: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://mysql.wmi.amu.edu.pl/s452376_pprog
    username: s452376
    password: 99031708874
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher