## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        ddl-auto: create
    show-sql: true
  database:
    driverClassName: org.hsqldb.jdbcDriver
  datasource:
    url: jdbc:hsqldb:mem:spring
    username: sa
    password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher