## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        hbm2ddl:
          auto: create
        show-sql: true
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/pprog
    username: postgres
    password: Halamadrid25
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher